# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 299)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.koltuk_7_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_7_btn.setEnabled(True)
        self.koltuk_7_btn.setGeometry(QtCore.QRect(449, 180, 50, 51))
        self.koltuk_7_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_7_btn.setFont(font)
        self.koltuk_7_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_7_btn.setAutoDefault(True)
        self.koltuk_7_btn.setDefault(True)
        self.koltuk_7_btn.setFlat(True)
        self.koltuk_7_btn.setObjectName("koltuk_7_btn")
        self.koltuk_11_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_11_btn.setEnabled(True)
        self.koltuk_11_btn.setGeometry(QtCore.QRect(549, 60, 50, 51))
        self.koltuk_11_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_11_btn.setFont(font)
        self.koltuk_11_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_11_btn.setAutoDefault(True)
        self.koltuk_11_btn.setDefault(True)
        self.koltuk_11_btn.setFlat(True)
        self.koltuk_11_btn.setObjectName("koltuk_11_btn")
        self.koltuk_10_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_10_btn.setEnabled(True)
        self.koltuk_10_btn.setGeometry(QtCore.QRect(499, 180, 50, 51))
        self.koltuk_10_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_10_btn.setFont(font)
        self.koltuk_10_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_10_btn.setAutoDefault(True)
        self.koltuk_10_btn.setDefault(True)
        self.koltuk_10_btn.setFlat(True)
        self.koltuk_10_btn.setObjectName("koltuk_10_btn")
        self.koltuk_1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_1_btn.setEnabled(True)
        self.koltuk_1_btn.setGeometry(QtCore.QRect(349, 60, 50, 51))
        self.koltuk_1_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.koltuk_1_btn.setFont(font)
        self.koltuk_1_btn.setAutoFillBackground(False)
        self.koltuk_1_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.koltuk_1_btn.setAutoDefault(True)
        self.koltuk_1_btn.setDefault(True)
        self.koltuk_1_btn.setFlat(True)
        self.koltuk_1_btn.setObjectName("koltuk_1_btn")
        self.koltuk_9_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_9_btn.setEnabled(True)
        self.koltuk_9_btn.setGeometry(QtCore.QRect(499, 130, 50, 51))
        self.koltuk_9_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_9_btn.setFont(font)
        self.koltuk_9_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_9_btn.setAutoDefault(True)
        self.koltuk_9_btn.setDefault(True)
        self.koltuk_9_btn.setFlat(True)
        self.koltuk_9_btn.setObjectName("koltuk_9_btn")
        self.koltuk_5_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_5_btn.setEnabled(True)
        self.koltuk_5_btn.setGeometry(QtCore.QRect(449, 60, 50, 51))
        self.koltuk_5_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_5_btn.setFont(font)
        self.koltuk_5_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_5_btn.setAutoDefault(True)
        self.koltuk_5_btn.setDefault(True)
        self.koltuk_5_btn.setFlat(True)
        self.koltuk_5_btn.setObjectName("koltuk_5_btn")
        self.koltuk_8_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_8_btn.setEnabled(True)
        self.koltuk_8_btn.setGeometry(QtCore.QRect(499, 60, 50, 51))
        self.koltuk_8_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_8_btn.setFont(font)
        self.koltuk_8_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_8_btn.setAutoDefault(True)
        self.koltuk_8_btn.setDefault(True)
        self.koltuk_8_btn.setFlat(True)
        self.koltuk_8_btn.setObjectName("koltuk_8_btn")
        self.koltuk_13_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_13_btn.setEnabled(True)
        self.koltuk_13_btn.setGeometry(QtCore.QRect(549, 180, 50, 51))
        self.koltuk_13_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_13_btn.setFont(font)
        self.koltuk_13_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_13_btn.setAutoDefault(True)
        self.koltuk_13_btn.setDefault(True)
        self.koltuk_13_btn.setFlat(True)
        self.koltuk_13_btn.setObjectName("koltuk_13_btn")
        self.koltuk_6_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_6_btn.setEnabled(True)
        self.koltuk_6_btn.setGeometry(QtCore.QRect(449, 130, 50, 51))
        self.koltuk_6_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_6_btn.setFont(font)
        self.koltuk_6_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_6_btn.setAutoDefault(True)
        self.koltuk_6_btn.setDefault(True)
        self.koltuk_6_btn.setFlat(True)
        self.koltuk_6_btn.setObjectName("koltuk_6_btn")
        self.koltuk_12_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_12_btn.setEnabled(True)
        self.koltuk_12_btn.setGeometry(QtCore.QRect(549, 130, 50, 51))
        self.koltuk_12_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_12_btn.setFont(font)
        self.koltuk_12_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_12_btn.setAutoDefault(True)
        self.koltuk_12_btn.setDefault(True)
        self.koltuk_12_btn.setFlat(True)
        self.koltuk_12_btn.setObjectName("koltuk_12_btn")
        self.koltuk_4_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_4_btn.setEnabled(True)
        self.koltuk_4_btn.setGeometry(QtCore.QRect(399, 180, 50, 51))
        self.koltuk_4_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_4_btn.setFont(font)
        self.koltuk_4_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_4_btn.setAutoDefault(True)
        self.koltuk_4_btn.setDefault(True)
        self.koltuk_4_btn.setFlat(True)
        self.koltuk_4_btn.setObjectName("koltuk_4_btn")
        self.koltuk_3_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_3_btn.setEnabled(True)
        self.koltuk_3_btn.setGeometry(QtCore.QRect(399, 130, 50, 51))
        self.koltuk_3_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_3_btn.setFont(font)
        self.koltuk_3_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.koltuk_3_btn.setAutoDefault(True)
        self.koltuk_3_btn.setDefault(True)
        self.koltuk_3_btn.setFlat(True)
        self.koltuk_3_btn.setObjectName("koltuk_3_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(349, 180, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/steering wheel.png"))
        self.label.setObjectName("label")
        self.koltuk_16_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_16_btn.setEnabled(True)
        self.koltuk_16_btn.setGeometry(QtCore.QRect(599, 180, 50, 51))
        self.koltuk_16_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_16_btn.setFont(font)
        self.koltuk_16_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_16_btn.setAutoDefault(True)
        self.koltuk_16_btn.setDefault(True)
        self.koltuk_16_btn.setFlat(True)
        self.koltuk_16_btn.setObjectName("koltuk_16_btn")
        self.koltuk_15_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_15_btn.setEnabled(True)
        self.koltuk_15_btn.setGeometry(QtCore.QRect(599, 130, 50, 51))
        self.koltuk_15_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_15_btn.setFont(font)
        self.koltuk_15_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_15_btn.setAutoDefault(True)
        self.koltuk_15_btn.setDefault(True)
        self.koltuk_15_btn.setFlat(True)
        self.koltuk_15_btn.setObjectName("koltuk_15_btn")
        self.koltuk_14_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_14_btn.setEnabled(True)
        self.koltuk_14_btn.setGeometry(QtCore.QRect(599, 60, 50, 51))
        self.koltuk_14_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_14_btn.setFont(font)
        self.koltuk_14_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"color: rgb(255, 255, 255);")
        self.koltuk_14_btn.setAutoDefault(True)
        self.koltuk_14_btn.setDefault(True)
        self.koltuk_14_btn.setFlat(True)
        self.koltuk_14_btn.setObjectName("koltuk_14_btn")
        self.koltuk_2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_2_btn.setEnabled(True)
        self.koltuk_2_btn.setGeometry(QtCore.QRect(349, 110, 50, 51))
        self.koltuk_2_btn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.koltuk_2_btn.setFont(font)
        self.koltuk_2_btn.setStyleSheet("background-image: url(img/free-seat.png);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center;\n"
"background-repeat: no-repeat;")
        self.koltuk_2_btn.setAutoDefault(True)
        self.koltuk_2_btn.setDefault(True)
        self.koltuk_2_btn.setFlat(True)
        self.koltuk_2_btn.setObjectName("koltuk_2_btn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(299, 40, 341, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(290, 50, 16, 191))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 22, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ad_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.ad_txt.setGeometry(QtCore.QRect(10, 24, 133, 20))
        self.ad_txt.setObjectName("ad_txt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 45, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.soyad_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.soyad_txt.setGeometry(QtCore.QRect(10, 74, 133, 20))
        self.soyad_txt.setObjectName("soyad_txt")
        self.cinsiyet_cbBox = QtWidgets.QComboBox(self.centralwidget)
        self.cinsiyet_cbBox.setGeometry(QtCore.QRect(150, 74, 64, 20))
        self.cinsiyet_cbBox.setObjectName("cinsiyet_cbBox")
        self.cinsiyet_cbBox.addItem("")
        self.cinsiyet_cbBox.addItem("")
        self.cinsiyet_cbBox.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(150, 24, 77, 20))
        self.dateEdit.setObjectName("dateEdit")
        self.time_cbBox = QtWidgets.QComboBox(self.centralwidget)
        self.time_cbBox.setGeometry(QtCore.QRect(150, 49, 54, 20))
        self.time_cbBox.setObjectName("time_cbBox")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 60, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.binis_TEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.binis_TEdit.setGeometry(QtCore.QRect(10, 124, 256, 51))
        self.binis_TEdit.setObjectName("binis_TEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 52, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inis_TEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.inis_TEdit.setGeometry(QtCore.QRect(10, 204, 256, 41))
        self.inis_TEdit.setObjectName("inis_TEdit")
        self.kaydet_btn = QtWidgets.QPushButton(self.centralwidget)
        self.kaydet_btn.setGeometry(QtCore.QRect(190, 250, 75, 23))
        self.kaydet_btn.setObjectName("kaydet_btn")
        self.temizle_btn = QtWidgets.QPushButton(self.centralwidget)
        self.temizle_btn.setGeometry(QtCore.QRect(100, 250, 75, 23))
        self.temizle_btn.setObjectName("temizle_btn")
        self.iptal_btn = QtWidgets.QPushButton(self.centralwidget)
        self.iptal_btn.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.iptal_btn.setObjectName("iptal_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.koltuklar = [
            self.koltuk_1_btn,
            self.koltuk_2_btn,
            self.koltuk_3_btn,
            self.koltuk_4_btn,
            self.koltuk_5_btn,
            self.koltuk_6_btn,
            self.koltuk_7_btn,
            self.koltuk_8_btn,
            self.koltuk_9_btn,
            self.koltuk_10_btn,
            self.koltuk_11_btn,
            self.koltuk_12_btn,
            self.koltuk_13_btn,
            self.koltuk_14_btn,
            self.koltuk_15_btn,
            self.koltuk_16_btn
        ]

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.koltuk_7_btn.setText(_translate("MainWindow", " 7"))
        self.koltuk_11_btn.setText(_translate("MainWindow", "  11"))
        self.koltuk_10_btn.setText(_translate("MainWindow", "  10"))
        self.koltuk_1_btn.setText(_translate("MainWindow", " 1"))
        self.koltuk_9_btn.setText(_translate("MainWindow", " 9"))
        self.koltuk_5_btn.setText(_translate("MainWindow", " 5"))
        self.koltuk_8_btn.setText(_translate("MainWindow", " 8"))
        self.koltuk_13_btn.setText(_translate("MainWindow", "  13"))
        self.koltuk_6_btn.setText(_translate("MainWindow", " 6"))
        self.koltuk_12_btn.setText(_translate("MainWindow", "  12"))
        self.koltuk_4_btn.setText(_translate("MainWindow", " 4"))
        self.koltuk_3_btn.setText(_translate("MainWindow", " 3"))
        self.koltuk_16_btn.setText(_translate("MainWindow", "  16"))
        self.koltuk_15_btn.setText(_translate("MainWindow", "  15"))
        self.koltuk_14_btn.setText(_translate("MainWindow", "  14"))
        self.koltuk_2_btn.setText(_translate("MainWindow", " 2"))
        self.label_2.setText(_translate("MainWindow", "Ad:"))
        self.label_3.setText(_translate("MainWindow", "Soyad:"))
        self.cinsiyet_cbBox.setItemText(0, _translate("MainWindow", "Cinsiyet"))
        self.cinsiyet_cbBox.setItemText(1, _translate("MainWindow", "Erkek"))
        self.cinsiyet_cbBox.setItemText(2, _translate("MainWindow", "Kadın"))
        self.time_cbBox.setItemText(0, _translate("MainWindow", "08:00"))
        self.time_cbBox.setItemText(1, _translate("MainWindow", "12:00"))
        self.time_cbBox.setItemText(2, _translate("MainWindow", "15:00"))
        self.time_cbBox.setItemText(3, _translate("MainWindow", "18:00"))
        self.label_4.setText(_translate("MainWindow", "Nereden:"))
        self.label_5.setText(_translate("MainWindow", "Nereye:"))
        self.kaydet_btn.setText(_translate("MainWindow", "Kaydet"))
        self.temizle_btn.setText(_translate("MainWindow", "Temizle"))
        self.iptal_btn.setText(_translate("MainWindow", "İptal"))
