# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otobus.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 252, 947, 287))
        self.label.setStyleSheet("background-image:url(:/img/img/otobus.png);background-position: center;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.koltuk_1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_1_btn.setGeometry(QtCore.QRect(95, 463, 55, 70))
        self.koltuk_1_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_1_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_1_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_1_btn.setObjectName("koltuk_1_btn")
        self.koltuk_4_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_4_btn.setGeometry(QtCore.QRect(160, 463, 55, 70))
        self.koltuk_4_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_4_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_4_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_4_btn.setObjectName("koltuk_4_btn")
        self.koltuk_7_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_7_btn.setGeometry(QtCore.QRect(225, 463, 55, 70))
        self.koltuk_7_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_7_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_7_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_7_btn.setObjectName("koltuk_7_btn")
        self.koltuk_16_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_16_btn.setGeometry(QtCore.QRect(420, 463, 55, 70))
        self.koltuk_16_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_16_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_16_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_16_btn.setObjectName("koltuk_16_btn")
        self.koltuk_13_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_13_btn.setGeometry(QtCore.QRect(355, 463, 55, 70))
        self.koltuk_13_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_13_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_13_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_13_btn.setObjectName("koltuk_13_btn")
        self.koltuk_10_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_10_btn.setGeometry(QtCore.QRect(290, 463, 55, 70))
        self.koltuk_10_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_10_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_10_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_10_btn.setObjectName("koltuk_10_btn")
        self.koltuk_19_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_19_btn.setGeometry(QtCore.QRect(485, 463, 55, 70))
        self.koltuk_19_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_19_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_19_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_19_btn.setObjectName("koltuk_19_btn")
        self.koltuk_32_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_32_btn.setGeometry(QtCore.QRect(810, 463, 55, 70))
        self.koltuk_32_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_32_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_32_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_32_btn.setObjectName("koltuk_32_btn")
        self.koltuk_26_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_26_btn.setGeometry(QtCore.QRect(680, 463, 55, 70))
        self.koltuk_26_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_26_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_26_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_26_btn.setObjectName("koltuk_26_btn")
        self.koltuk_20_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_20_btn.setGeometry(QtCore.QRect(550, 463, 55, 70))
        self.koltuk_20_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_20_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_20_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_20_btn.setObjectName("koltuk_20_btn")
        self.koltuk_29_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_29_btn.setGeometry(QtCore.QRect(745, 463, 55, 70))
        self.koltuk_29_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_29_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_29_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_29_btn.setObjectName("koltuk_29_btn")
        self.koltuk_23_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_23_btn.setGeometry(QtCore.QRect(615, 463, 55, 70))
        self.koltuk_23_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_23_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_23_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_23_btn.setObjectName("koltuk_23_btn")
        self.koltuk_2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_2_btn.setGeometry(QtCore.QRect(95, 339, 55, 70))
        self.koltuk_2_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_2_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_2_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_2_btn.setObjectName("koltuk_2_btn")
        self.koltuk_3_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_3_btn.setGeometry(QtCore.QRect(95, 262, 55, 70))
        self.koltuk_3_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_3_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_3_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_3_btn.setObjectName("koltuk_3_btn")
        self.koltuk_35_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_35_btn.setGeometry(QtCore.QRect(875, 463, 55, 70))
        self.koltuk_35_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_35_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_35_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_35_btn.setObjectName("koltuk_35_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(660, 545, 25, 25))
        self.label_2.setMinimumSize(QtCore.QSize(25, 25))
        self.label_2.setStyleSheet("background-color: rgb(149, 149, 149);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 545, 35, 25))
        self.label_3.setMinimumSize(QtCore.QSize(35, 25))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(756, 545, 45, 25))
        self.label_4.setMinimumSize(QtCore.QSize(45, 25))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(726, 545, 25, 25))
        self.label_5.setMinimumSize(QtCore.QSize(25, 25))
        self.label_5.setStyleSheet("background-color: rgb(255, 112, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(804, 545, 25, 25))
        self.label_6.setMinimumSize(QtCore.QSize(25, 25))
        self.label_6.setStyleSheet("background-color: rgb(0, 174, 239);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(834, 545, 35, 25))
        self.label_7.setMinimumSize(QtCore.QSize(35, 25))
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(870, 545, 25, 25))
        self.label_8.setMinimumSize(QtCore.QSize(25, 25))
        self.label_8.setStyleSheet("background-color: rgb(114, 255, 54);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(900, 545, 45, 25))
        self.label_9.setMinimumSize(QtCore.QSize(45, 25))
        self.label_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.koltuk_5_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_5_btn.setGeometry(QtCore.QRect(160, 339, 55, 70))
        self.koltuk_5_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_5_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_5_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_5_btn.setObjectName("koltuk_5_btn")
        self.koltuk_6_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_6_btn.setGeometry(QtCore.QRect(160, 262, 55, 70))
        self.koltuk_6_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_6_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_6_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_6_btn.setObjectName("koltuk_6_btn")
        self.koltuk_14_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_14_btn.setGeometry(QtCore.QRect(355, 340, 55, 70))
        self.koltuk_14_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_14_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_14_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_14_btn.setObjectName("koltuk_14_btn")
        self.koltuk_15_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_15_btn.setGeometry(QtCore.QRect(355, 262, 55, 70))
        self.koltuk_15_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_15_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_15_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_15_btn.setObjectName("koltuk_15_btn")
        self.koltuk_17_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_17_btn.setGeometry(QtCore.QRect(420, 340, 55, 70))
        self.koltuk_17_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_17_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_17_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_17_btn.setObjectName("koltuk_17_btn")
        self.koltuk_18_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_18_btn.setGeometry(QtCore.QRect(420, 262, 55, 70))
        self.koltuk_18_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_18_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_18_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_18_btn.setObjectName("koltuk_18_btn")
        self.koltuk_12_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_12_btn.setGeometry(QtCore.QRect(290, 262, 55, 70))
        self.koltuk_12_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_12_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_12_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_12_btn.setObjectName("koltuk_12_btn")
        self.koltuk_11_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_11_btn.setGeometry(QtCore.QRect(290, 339, 55, 70))
        self.koltuk_11_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_11_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_11_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_11_btn.setObjectName("koltuk_11_btn")
        self.koltuk_9_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_9_btn.setGeometry(QtCore.QRect(225, 262, 55, 70))
        self.koltuk_9_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_9_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_9_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_9_btn.setObjectName("koltuk_9_btn")
        self.koltuk_8_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_8_btn.setGeometry(QtCore.QRect(225, 339, 55, 70))
        self.koltuk_8_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_8_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_8_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_8_btn.setObjectName("koltuk_8_btn")
        self.koltuk_25_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_25_btn.setGeometry(QtCore.QRect(615, 262, 55, 70))
        self.koltuk_25_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_25_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_25_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_25_btn.setObjectName("koltuk_25_btn")
        self.koltuk_24_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_24_btn.setGeometry(QtCore.QRect(615, 340, 55, 70))
        self.koltuk_24_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_24_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_24_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_24_btn.setObjectName("koltuk_24_btn")
        self.koltuk_27_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_27_btn.setGeometry(QtCore.QRect(680, 340, 55, 70))
        self.koltuk_27_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_27_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_27_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_27_btn.setObjectName("koltuk_27_btn")
        self.koltuk_28_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_28_btn.setGeometry(QtCore.QRect(680, 262, 55, 70))
        self.koltuk_28_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_28_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_28_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_28_btn.setObjectName("koltuk_28_btn")
        self.koltuk_34_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_34_btn.setGeometry(QtCore.QRect(810, 262, 55, 70))
        self.koltuk_34_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_34_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_34_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_34_btn.setObjectName("koltuk_34_btn")
        self.koltuk_33_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_33_btn.setGeometry(QtCore.QRect(810, 340, 55, 70))
        self.koltuk_33_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_33_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_33_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_33_btn.setObjectName("koltuk_33_btn")
        self.koltuk_36_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_36_btn.setGeometry(QtCore.QRect(875, 340, 55, 70))
        self.koltuk_36_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_36_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_36_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_36_btn.setObjectName("koltuk_36_btn")
        self.koltuk_37_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_37_btn.setGeometry(QtCore.QRect(875, 262, 55, 70))
        self.koltuk_37_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_37_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_37_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_37_btn.setObjectName("koltuk_37_btn")
        self.koltuk_31_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_31_btn.setGeometry(QtCore.QRect(745, 262, 55, 70))
        self.koltuk_31_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_31_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_31_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_31_btn.setObjectName("koltuk_31_btn")
        self.koltuk_30_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_30_btn.setGeometry(QtCore.QRect(745, 340, 55, 70))
        self.koltuk_30_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_30_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_30_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_30_btn.setObjectName("koltuk_30_btn")
        self.koltuk_22_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_22_btn.setGeometry(QtCore.QRect(550, 262, 55, 70))
        self.koltuk_22_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_22_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_22_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_22_btn.setObjectName("koltuk_22_btn")
        self.koltuk_21_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_21_btn.setGeometry(QtCore.QRect(550, 340, 55, 70))
        self.koltuk_21_btn.setMinimumSize(QtCore.QSize(55, 70))
        self.koltuk_21_btn.setMaximumSize(QtCore.QSize(55, 16777215))
        self.koltuk_21_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_21_btn.setObjectName("koltuk_21_btn")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 130, 412, 112))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setEnabled(True)
        self.label_10.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.ad_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.ad_txt.setObjectName("ad_txt")
        self.horizontalLayout.addWidget(self.ad_txt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.soyad_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.soyad_txt.setObjectName("soyad_txt")
        self.horizontalLayout_2.addWidget(self.soyad_txt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.binis_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.binis_txt.setObjectName("binis_txt")
        self.horizontalLayout_3.addWidget(self.binis_txt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.inis_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.inis_txt.setObjectName("inis_txt")
        self.horizontalLayout_4.addWidget(self.inis_txt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.cinsiyet_cbBox = QtWidgets.QComboBox(self.layoutWidget)
        self.cinsiyet_cbBox.setMinimumSize(QtCore.QSize(80, 0))
        self.cinsiyet_cbBox.setObjectName("cinsiyet_cbBox")
        self.cinsiyet_cbBox.addItem("")
        self.cinsiyet_cbBox.addItem("")
        self.cinsiyet_cbBox.addItem("")
        self.horizontalLayout_5.addWidget(self.cinsiyet_cbBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.time_cbBox = QtWidgets.QComboBox(self.layoutWidget)
        self.time_cbBox.setMinimumSize(QtCore.QSize(80, 0))
        self.time_cbBox.setObjectName("time_cbBox")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.horizontalLayout_6.addWidget(self.time_cbBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(45, 0))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setDate(QtCore.QDate(2019, 12, 7))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_7.addWidget(self.dateEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.kaydet_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.kaydet_btn.setObjectName("kaydet_btn")
        self.verticalLayout_8.addWidget(self.kaydet_btn)
        self.temizle_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.temizle_btn.setObjectName("temizle_btn")
        self.verticalLayout_8.addWidget(self.temizle_btn)
        self.iptal_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.iptal_btn.setObjectName("iptal_btn")
        self.verticalLayout_8.addWidget(self.iptal_btn)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.koltuk_1_btn.setText(_translate("MainWindow", "1"))
        self.koltuk_4_btn.setText(_translate("MainWindow", "4"))
        self.koltuk_7_btn.setText(_translate("MainWindow", "7"))
        self.koltuk_16_btn.setText(_translate("MainWindow", "16"))
        self.koltuk_13_btn.setText(_translate("MainWindow", "13"))
        self.koltuk_10_btn.setText(_translate("MainWindow", "10"))
        self.koltuk_19_btn.setText(_translate("MainWindow", "19"))
        self.koltuk_32_btn.setText(_translate("MainWindow", "32"))
        self.koltuk_26_btn.setText(_translate("MainWindow", "26"))
        self.koltuk_20_btn.setText(_translate("MainWindow", "20"))
        self.koltuk_29_btn.setText(_translate("MainWindow", "29"))
        self.koltuk_23_btn.setText(_translate("MainWindow", "23"))
        self.koltuk_2_btn.setText(_translate("MainWindow", "2"))
        self.koltuk_3_btn.setText(_translate("MainWindow", "3"))
        self.koltuk_35_btn.setText(_translate("MainWindow", "35"))
        self.label_3.setText(_translate("MainWindow", "Boş"))
        self.label_4.setText(_translate("MainWindow", "Bayan"))
        self.label_7.setText(_translate("MainWindow", "Bay"))
        self.label_9.setText(_translate("MainWindow", "Seçili"))
        self.koltuk_5_btn.setText(_translate("MainWindow", "5"))
        self.koltuk_6_btn.setText(_translate("MainWindow", "6"))
        self.koltuk_14_btn.setText(_translate("MainWindow", "14"))
        self.koltuk_15_btn.setText(_translate("MainWindow", "15"))
        self.koltuk_17_btn.setText(_translate("MainWindow", "17"))
        self.koltuk_18_btn.setText(_translate("MainWindow", "18"))
        self.koltuk_12_btn.setText(_translate("MainWindow", "12"))
        self.koltuk_11_btn.setText(_translate("MainWindow", "11"))
        self.koltuk_9_btn.setText(_translate("MainWindow", "9"))
        self.koltuk_8_btn.setText(_translate("MainWindow", "8"))
        self.koltuk_25_btn.setText(_translate("MainWindow", "25"))
        self.koltuk_24_btn.setText(_translate("MainWindow", "24"))
        self.koltuk_27_btn.setText(_translate("MainWindow", "27"))
        self.koltuk_28_btn.setText(_translate("MainWindow", "28"))
        self.koltuk_34_btn.setText(_translate("MainWindow", "34"))
        self.koltuk_33_btn.setText(_translate("MainWindow", "33"))
        self.koltuk_36_btn.setText(_translate("MainWindow", "36"))
        self.koltuk_37_btn.setText(_translate("MainWindow", "37"))
        self.koltuk_31_btn.setText(_translate("MainWindow", "31"))
        self.koltuk_30_btn.setText(_translate("MainWindow", "30"))
        self.koltuk_22_btn.setText(_translate("MainWindow", "22"))
        self.koltuk_21_btn.setText(_translate("MainWindow", "21"))
        self.label_10.setText(_translate("MainWindow", "Ad"))
        self.label_11.setText(_translate("MainWindow", "Soyad"))
        self.label_12.setText(_translate("MainWindow", "Nerden"))
        self.label_13.setText(_translate("MainWindow", "Nereye"))
        self.label_14.setText(_translate("MainWindow", "Cinsiyet"))
        self.cinsiyet_cbBox.setItemText(0, _translate("MainWindow", "-"))
        self.cinsiyet_cbBox.setItemText(1, _translate("MainWindow", "Erkek"))
        self.cinsiyet_cbBox.setItemText(2, _translate("MainWindow", "Kadın"))
        self.label_15.setText(_translate("MainWindow", "Sefer"))
        self.time_cbBox.setItemText(0, _translate("MainWindow", "08:00"))
        self.time_cbBox.setItemText(1, _translate("MainWindow", "12:00"))
        self.time_cbBox.setItemText(2, _translate("MainWindow", "18:00"))
        self.label_16.setText(_translate("MainWindow", "Tarih"))
        self.kaydet_btn.setText(_translate("MainWindow", "Kaydet"))
        self.temizle_btn.setText(_translate("MainWindow", "Temizle"))
        self.iptal_btn.setText(_translate("MainWindow", "İptal"))
import resources.assets
