# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainscreen.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, 20, 20, 531))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 316, 539))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ad_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.ad_txt.setObjectName("ad_txt")
        self.verticalLayout.addWidget(self.ad_txt)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.soyad_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.soyad_txt.setObjectName("soyad_txt")
        self.verticalLayout.addWidget(self.soyad_txt)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.telNo_txt = QtWidgets.QLineEdit(self.layoutWidget)
        self.telNo_txt.setObjectName("telNo_txt")
        self.verticalLayout.addWidget(self.telNo_txt)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.cinsiyet_cbBox = QtWidgets.QComboBox(self.layoutWidget)
        self.cinsiyet_cbBox.setObjectName("cinsiyet_cbBox")
        self.cinsiyet_cbBox.addItem("")
        self.cinsiyet_cbBox.addItem("")
        self.cinsiyet_cbBox.addItem("")
        self.verticalLayout.addWidget(self.cinsiyet_cbBox)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.durak_cbBox = QtWidgets.QComboBox(self.layoutWidget)
        self.durak_cbBox.setObjectName("durak_cbBox")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.durak_cbBox.addItem("")
        self.verticalLayout.addWidget(self.durak_cbBox)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.time_cbBox = QtWidgets.QComboBox(self.layoutWidget)
        self.time_cbBox.setObjectName("time_cbBox")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.time_cbBox.addItem("")
        self.verticalLayout.addWidget(self.time_cbBox)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.dateEdit = QtWidgets.QCalendarWidget(self.layoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.kaydet_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.kaydet_btn.setAutoDefault(False)
        self.kaydet_btn.setDefault(False)
        self.kaydet_btn.setFlat(False)
        self.kaydet_btn.setObjectName("kaydet_btn")
        self.verticalLayout_2.addWidget(self.kaydet_btn)
        self.koltuk_3_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_3_btn.setGeometry(QtCore.QRect(380, 80, 50, 40))
        self.koltuk_3_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_3_btn.setObjectName("koltuk_3_btn")
        self.koltuk_5_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_5_btn.setGeometry(QtCore.QRect(380, 130, 50, 40))
        self.koltuk_5_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_5_btn.setObjectName("koltuk_5_btn")
        self.koltuk_8_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_8_btn.setGeometry(QtCore.QRect(380, 180, 50, 40))
        self.koltuk_8_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_8_btn.setObjectName("koltuk_8_btn")
        self.koltuk_11_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_11_btn.setGeometry(QtCore.QRect(380, 230, 50, 40))
        self.koltuk_11_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_11_btn.setObjectName("koltuk_11_btn")
        self.koltuk_14_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_14_btn.setGeometry(QtCore.QRect(380, 280, 50, 40))
        self.koltuk_14_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_14_btn.setObjectName("koltuk_14_btn")
        self.koltuk_17_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_17_btn.setGeometry(QtCore.QRect(380, 330, 50, 40))
        self.koltuk_17_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_17_btn.setObjectName("koltuk_17_btn")
        self.koltuk_18_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_18_btn.setGeometry(QtCore.QRect(440, 330, 50, 40))
        self.koltuk_18_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_18_btn.setObjectName("koltuk_18_btn")
        self.koltuk_15_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_15_btn.setGeometry(QtCore.QRect(440, 280, 50, 40))
        self.koltuk_15_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_15_btn.setObjectName("koltuk_15_btn")
        self.koltuk_6_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_6_btn.setGeometry(QtCore.QRect(440, 130, 50, 40))
        self.koltuk_6_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_6_btn.setObjectName("koltuk_6_btn")
        self.koltuk_4_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_4_btn.setGeometry(QtCore.QRect(440, 80, 50, 40))
        self.koltuk_4_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_4_btn.setObjectName("koltuk_4_btn")
        self.koltuk_12_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_12_btn.setGeometry(QtCore.QRect(440, 230, 50, 40))
        self.koltuk_12_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_12_btn.setObjectName("koltuk_12_btn")
        self.koltuk_9_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_9_btn.setGeometry(QtCore.QRect(440, 180, 50, 40))
        self.koltuk_9_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_9_btn.setObjectName("koltuk_9_btn")
        self.koltuk_20_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_20_btn.setGeometry(QtCore.QRect(560, 330, 50, 40))
        self.koltuk_20_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_20_btn.setObjectName("koltuk_20_btn")
        self.koltuk_19_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_19_btn.setGeometry(QtCore.QRect(500, 330, 50, 40))
        self.koltuk_19_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_19_btn.setObjectName("koltuk_19_btn")
        self.koltuk_10_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_10_btn.setGeometry(QtCore.QRect(560, 180, 50, 40))
        self.koltuk_10_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_10_btn.setObjectName("koltuk_10_btn")
        self.koltuk_7_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_7_btn.setGeometry(QtCore.QRect(560, 130, 50, 40))
        self.koltuk_7_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_7_btn.setObjectName("koltuk_7_btn")
        self.koltuk_16_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_16_btn.setGeometry(QtCore.QRect(560, 280, 50, 40))
        self.koltuk_16_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_16_btn.setObjectName("koltuk_16_btn")
        self.koltuk_13_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_13_btn.setGeometry(QtCore.QRect(560, 230, 50, 40))
        self.koltuk_13_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_13_btn.setObjectName("koltuk_13_btn")
        self.koltuk_2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_2_btn.setGeometry(QtCore.QRect(560, 30, 50, 40))
        self.koltuk_2_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_2_btn.setObjectName("koltuk_2_btn")
        self.koltuk_1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.koltuk_1_btn.setGeometry(QtCore.QRect(500, 30, 50, 40))
        self.koltuk_1_btn.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/free-seat.png);background-position: center;background-repeat: no-repeat;")
        self.koltuk_1_btn.setObjectName("koltuk_1_btn")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(620, 20, 20, 531))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.steering_whell = QtWidgets.QPushButton(self.centralwidget)
        self.steering_whell.setGeometry(QtCore.QRect(380, 30, 50, 40))
        self.steering_whell.setStyleSheet("font: 75 17pt \"Consolas\";border: 0px;background-image: url(:/img/img/steering-whell.png);background-position: center;background-repeat: no-repeat;")
        self.steering_whell.setText("")
        self.steering_whell.setObjectName("steering_whell")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Adı:"))
        self.label_2.setText(_translate("MainWindow", "Soyadı:"))
        self.label_3.setText(_translate("MainWindow", "Telefon No:"))
        self.label_6.setText(_translate("MainWindow", "Cinsiyet:"))
        self.cinsiyet_cbBox.setItemText(0, _translate("MainWindow", "Cinsiyet Seçin"))
        self.cinsiyet_cbBox.setItemText(1, _translate("MainWindow", "Kadın"))
        self.cinsiyet_cbBox.setItemText(2, _translate("MainWindow", "Erkek"))
        self.label_4.setText(_translate("MainWindow", "Durak:"))
        self.durak_cbBox.setItemText(0, _translate("MainWindow", "CİDE-DAĞLI"))
        self.durak_cbBox.setItemText(1, _translate("MainWindow", "CİDE-CELALLI"))
        self.durak_cbBox.setItemText(2, _translate("MainWindow", "CİDE-H.GİRİŞ"))
        self.durak_cbBox.setItemText(3, _translate("MainWindow", "CİDE-ŞENPAZAR"))
        self.durak_cbBox.setItemText(4, _translate("MainWindow", "CİDE-KALAYCI"))
        self.durak_cbBox.setItemText(5, _translate("MainWindow", "CİDE-VALAY-SADA"))
        self.durak_cbBox.setItemText(6, _translate("MainWindow", "CİDE-AĞLI"))
        self.durak_cbBox.setItemText(7, _translate("MainWindow", "CİDE SEYDİLER"))
        self.durak_cbBox.setItemText(8, _translate("MainWindow", "CİDE-DVRKİ-KASTAMONU"))
        self.durak_cbBox.setItemText(9, _translate("MainWindow", "KASTAMONU-SADA"))
        self.durak_cbBox.setItemText(10, _translate("MainWindow", "KASTAMONU-DERELİ"))
        self.durak_cbBox.setItemText(11, _translate("MainWindow", "KASTAMONU-VALAY"))
        self.durak_cbBox.setItemText(12, _translate("MainWindow", "KASTAMONU-ŞENPAZAR"))
        self.durak_cbBox.setItemText(13, _translate("MainWindow", "KASTAMONU-H.GİRİŞ"))
        self.durak_cbBox.setItemText(14, _translate("MainWindow", "KASTAMONU-DAĞLI"))
        self.durak_cbBox.setItemText(15, _translate("MainWindow", "KASTAMONU-CİDE"))
        self.label_5.setText(_translate("MainWindow", "Saat:"))
        self.time_cbBox.setItemText(0, _translate("MainWindow", "08:00"))
        self.time_cbBox.setItemText(1, _translate("MainWindow", "12:00"))
        self.time_cbBox.setItemText(2, _translate("MainWindow", "15:00"))
        self.time_cbBox.setItemText(3, _translate("MainWindow", "16:00"))
        self.label_7.setText(_translate("MainWindow", "Tarih:"))
        self.kaydet_btn.setText(_translate("MainWindow", "Kaydet"))
        self.koltuk_3_btn.setText(_translate("MainWindow", "3"))
        self.koltuk_5_btn.setText(_translate("MainWindow", "5"))
        self.koltuk_8_btn.setText(_translate("MainWindow", "8"))
        self.koltuk_11_btn.setText(_translate("MainWindow", "11"))
        self.koltuk_14_btn.setText(_translate("MainWindow", "14"))
        self.koltuk_17_btn.setText(_translate("MainWindow", "17"))
        self.koltuk_18_btn.setText(_translate("MainWindow", "18"))
        self.koltuk_15_btn.setText(_translate("MainWindow", "15"))
        self.koltuk_6_btn.setText(_translate("MainWindow", "6"))
        self.koltuk_4_btn.setText(_translate("MainWindow", "4"))
        self.koltuk_12_btn.setText(_translate("MainWindow", "12"))
        self.koltuk_9_btn.setText(_translate("MainWindow", "9"))
        self.koltuk_20_btn.setText(_translate("MainWindow", "20"))
        self.koltuk_19_btn.setText(_translate("MainWindow", "19"))
        self.koltuk_10_btn.setText(_translate("MainWindow", "10"))
        self.koltuk_7_btn.setText(_translate("MainWindow", "7"))
        self.koltuk_16_btn.setText(_translate("MainWindow", "16"))
        self.koltuk_13_btn.setText(_translate("MainWindow", "13"))
        self.koltuk_2_btn.setText(_translate("MainWindow", "2"))
        self.koltuk_1_btn.setText(_translate("MainWindow", "1"))
import resources.assets
